### ISSUE TITLE
major issue

### ISSUE THREAD

**Issue by MoleTheDev** [RexiRexii/anya-hook#1]
being too perfect 
<img src="https://c.tenor.com/D1auZTFc3vsAAAAd/sheesh.gif">

**Comment by RexiRexii** [comment]
u r too perfect <3

**Comment by RealNickk** [comment]
cringe

**Comment by MoleTheDev** [comment]
@RealNickk 
i will hunt u nick (⁠人⁠*⁠´⁠∀⁠｀⁠)⁠｡⁠*ﾟ⁠+

**Comment by RealNickk** [comment]
> @RealNickk 
> 
> i will hunt u nick (⁠人⁠*⁠´⁠∀⁠｀⁠)⁠｡⁠*ﾟ⁠+

cringe x2
